name: CI – Build, Test, Coverage, Sonar, Publish

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Cucumber tags to run (e.g. @smoke)'
        default: '@smoke'
      threadCount:
        description: 'Thread count for parallel tests'
        default: '2'
      parallel:
        description: 'Parallel mode (methods/classes/scenarios)'
        default: 'methods'
      env:
        description: 'Environment (dev/qa/prod)'
        default: 'sit'
      runnerLabel:
        description: 'Optional self-hosted runner label (runner-1, runner-2…)'
        default: 'runner-1'

permissions:
  contents: write
  pages: write       # Required to deploy to GitHub Pages
  id-token: write    # Required for authentication with Pages

jobs:
  tests:
    runs-on: ${{ fromJSON(inputs.runnerLabel != '' && format('["self-hosted", "{0}"]', inputs.runnerLabel) || '["self-hosted"]') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build & Test
        shell: powershell
        run: |
          echo "Running tests with:"
          echo "Tags: ${{ inputs.tags }}"
          echo "Thread count: ${{ inputs.threadCount }}"
          echo "Parallel: ${{ inputs.parallel }}"
          echo "Env: ${{ inputs.env }}"
          mvn -B clean verify `
            "-Dcucumber.filter.tags=${{ inputs.tags }}" `
            "-DthreadCount=${{ inputs.threadCount }}" `
            "-Dparallel=${{ inputs.parallel }}" `
            "-Denv=${{ inputs.env }}"

      # Upload the entire 'dashboard' folder as an artifact.
      - name: Upload Dynamic Report
        uses: actions/upload-artifact@v4
        with:
          name: dynamic-report
          path: dashboard

  # The 'publish-dashboard' job was incorrectly indented. It must be a top-level job.
  publish-dashboard:
    if: github.ref == 'refs/heads/gh-pages'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ${{ fromJSON(inputs.runnerLabel != '' && format('["self-hosted", "{0}"]', inputs.runnerLabel) || '["self-hosted"]') }}
    needs: tests

    concurrency:
      group: "pages"
      cancel-in-progress: true

    steps:
      - name: Download Dynamic Report
        uses: actions/download-artifact@v4
        with:
          name: dynamic-report
          path: dynamic-report

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload Report Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dynamic-report'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  sonar:
    runs-on: ${{ fromJSON(inputs.runnerLabel != '' && format('["self-hosted", "{0}"]', inputs.runnerLabel) || '["self-hosted"]') }}
    needs: tests
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run SonarCloud Scan
        shell: powershell
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn -B verify sonar:sonar `
            "-DskipTests" `
            "-Dsonar.organization=mohanpalekar" `
            "-Dsonar.projectKey=qa-bdd-framework" `
            "-Dsonar.host.url=https://sonarcloud.io" `
            "-Dsonar.login=${{ env.SONAR_TOKEN }}" `
            "-Dsonar.java.binaries=target/classes"
