name: CI – Build, Test, Coverage, Sonar, Publish

on:
  # push:
  #   branches: [ main ]
  # pull_request:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Cucumber tags to run (e.g. @smoke)'
        default: ''
      threadCount:
        description: 'Thread count for parallel tests'
        default: '5'
      parallel:
        description: 'Parallel mode (methods/classes/scenarios)'
        default: 'methods'
      env:
        description: 'Environment (dev/qa/prod)'
        default: 'dev'
      runnerLabel:
        description: 'Optional self-hosted runner label (runner1, runner2…) leave blank for any'
        default: ''

jobs:
  tests:
    # Pick a specific runner or any self-hosted Windows runner
    runs-on: ${{ inputs.runnerLabel != '' && format('[self-hosted, Windows, {0}]', inputs.runnerLabel) || '[self-hosted, Windows]' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven repo
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build & Test
        shell: pwsh
        run: |
          echo "Running tests with:"
          echo "Tags: ${{ github.event.inputs.tags }}"
          echo "Thread count: ${{ github.event.inputs.threadCount }}"
          echo "Parallel: ${{ github.event.inputs.parallel }}"
          echo "Env: ${{ github.event.inputs.env }}"
          mvn -B clean verify `
            -Dcucumber.filter.tags="${{ github.event.inputs.tags }}" `
            -DthreadCount=${{ github.event.inputs.threadCount }} `
            -Dparallel=${{ github.event.inputs.parallel }} `
            -Denv=${{ github.event.inputs.env }}

      - name: Upload JaCoCo HTML report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco

  publish:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download JaCoCo report
        uses: actions/download-artifact@v4
        with:
          name: jacoco-report
          path: jacoco

      - name: Deploy HTML coverage to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: jacoco

  sonar:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven repo
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn -B sonar:sonar \
            -Dsonar.organization=your-org \
            -Dsonar.projectKey=your-project-key \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${SONAR_TOKEN}
