name: CI – Build, Test, Coverage, Sonar, Publish

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Cucumber tags to run (e.g. @smoke)'
        default: '@smoke'
      threadCount:
        description: 'Thread count for parallel tests'
        default: '2'
      parallel:
        description: 'Parallel mode (methods/classes/scenarios)'
        default: 'methods'
      env:
        description: 'Environment (dev/qa/prod)'
        default: 'sit'
      runnerLabel:
        description: 'Optional self-hosted runner label (runner-1, runner-2…)'
        default: ''

permissions:
  contents: write  # Required for GitHub Pages deployment

jobs:
  tests:
    runs-on: ${{ fromJSON(inputs.runnerLabel != '' && format('["self-hosted", "{0}"]', inputs.runnerLabel) || '["self-hosted"]') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build & Test
        shell: powershell
        run: |
          echo "Running tests with:"
          echo "Tags: ${{ inputs.tags }}"
          echo "Thread count: ${{ inputs.threadCount }}"
          echo "Parallel: ${{ inputs.parallel }}"
          echo "Env: ${{ inputs.env }}"
          mvn -B clean verify `
            "-Dcucumber.filter.tags=${{ inputs.tags }}" `
            "-DthreadCount=${{ inputs.threadCount }}" `
            "-Dparallel=${{ inputs.parallel }}" `
            "-Denv=${{ inputs.env }}"

      - name: Upload JaCoCo HTML report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco

  publish:
    runs-on: ${{ fromJSON(inputs.runnerLabel != '' && format('["self-hosted", "{0}"]', inputs.runnerLabel) || '["self-hosted"]') }}
    needs: tests
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download JaCoCo report
        uses: actions/download-artifact@v4
        with:
          name: jacoco-report
          path: jacoco

      - name: Deploy HTML coverage to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: jacoco

  sonar:
    runs-on: ${{ fromJSON(inputs.runnerLabel != '' && format('["self-hosted", "{0}"]', inputs.runnerLabel) || '["self-hosted"]') }}
    needs: tests
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn -B sonar:sonar `
            -Dsonar.organization=your-org `
            -Dsonar.projectKey=your-project-key `
            -Dsonar.host.url=https://sonarcloud.io `
            -Dsonar.login=${SONAR_TOKEN}
